set_property SRC_FILE_INFO {cfile:D:/Project/Qt5Proj/win10/udpLoop/Qt_Udp_Loop/21_eth_udp_StreamIn/eth_udp_loop.srcs/constrs_1/new/eth_udp_loop.xdc rfile:../../../eth_udp_loop.srcs/constrs_1/new/eth_udp_loop.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports eth_rst_n]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports eth_rxc]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports eth_rx_ctl]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[0]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[1]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[2]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[3]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports eth_txc]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports eth_tx_ctl]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {eth_txd[0]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports {eth_txd[1]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports {eth_txd[2]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {eth_txd[3]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_gmii_to_rgmii/u_rgmii_rx/rgmii_txc]]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_gmii_to_rgmii/u_rgmii_rx/gmii_rx_clk]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_gmii_to_rgmii/u_rgmii_rx/rgmii_txc]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_fifo_ctrl/rec_fifo_din[0]} {u_fifo_ctrl/rec_fifo_din[1]} {u_fifo_ctrl/rec_fifo_din[2]} {u_fifo_ctrl/rec_fifo_din[3]} {u_fifo_ctrl/rec_fifo_din[4]} {u_fifo_ctrl/rec_fifo_din[5]} {u_fifo_ctrl/rec_fifo_din[6]} {u_fifo_ctrl/rec_fifo_din[7]} {u_fifo_ctrl/rec_fifo_din[8]} {u_fifo_ctrl/rec_fifo_din[9]} {u_fifo_ctrl/rec_fifo_din[10]} {u_fifo_ctrl/rec_fifo_din[11]} {u_fifo_ctrl/rec_fifo_din[12]} {u_fifo_ctrl/rec_fifo_din[13]} {u_fifo_ctrl/rec_fifo_din[14]} {u_fifo_ctrl/rec_fifo_din[15]} {u_fifo_ctrl/rec_fifo_din[16]} {u_fifo_ctrl/rec_fifo_din[17]} {u_fifo_ctrl/rec_fifo_din[18]} {u_fifo_ctrl/rec_fifo_din[19]} {u_fifo_ctrl/rec_fifo_din[20]} {u_fifo_ctrl/rec_fifo_din[21]} {u_fifo_ctrl/rec_fifo_din[22]} {u_fifo_ctrl/rec_fifo_din[23]} {u_fifo_ctrl/rec_fifo_din[24]} {u_fifo_ctrl/rec_fifo_din[25]} {u_fifo_ctrl/rec_fifo_din[26]} {u_fifo_ctrl/rec_fifo_din[27]} {u_fifo_ctrl/rec_fifo_din[28]} {u_fifo_ctrl/rec_fifo_din[29]} {u_fifo_ctrl/rec_fifo_din[30]} {u_fifo_ctrl/rec_fifo_din[31]}]]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_fifo_ctrl/num[0]} {u_fifo_ctrl/num[1]} {u_fifo_ctrl/num[2]} {u_fifo_ctrl/num[3]} {u_fifo_ctrl/num[4]} {u_fifo_ctrl/num[5]} {u_fifo_ctrl/num[6]} {u_fifo_ctrl/num[7]} {u_fifo_ctrl/num[8]} {u_fifo_ctrl/num[9]} {u_fifo_ctrl/num[10]} {u_fifo_ctrl/num[11]} {u_fifo_ctrl/num[12]} {u_fifo_ctrl/num[13]} {u_fifo_ctrl/num[14]} {u_fifo_ctrl/num[15]}]]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_fifo_ctrl/rec_byte_num[0]} {u_fifo_ctrl/rec_byte_num[1]} {u_fifo_ctrl/rec_byte_num[2]} {u_fifo_ctrl/rec_byte_num[3]} {u_fifo_ctrl/rec_byte_num[4]} {u_fifo_ctrl/rec_byte_num[5]} {u_fifo_ctrl/rec_byte_num[6]} {u_fifo_ctrl/rec_byte_num[7]} {u_fifo_ctrl/rec_byte_num[8]} {u_fifo_ctrl/rec_byte_num[9]} {u_fifo_ctrl/rec_byte_num[10]} {u_fifo_ctrl/rec_byte_num[11]} {u_fifo_ctrl/rec_byte_num[12]} {u_fifo_ctrl/rec_byte_num[13]} {u_fifo_ctrl/rec_byte_num[14]} {u_fifo_ctrl/rec_byte_num[15]}]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_fifo_ctrl/fpga2pc_fifo_din[0]} {u_fifo_ctrl/fpga2pc_fifo_din[1]} {u_fifo_ctrl/fpga2pc_fifo_din[2]} {u_fifo_ctrl/fpga2pc_fifo_din[3]} {u_fifo_ctrl/fpga2pc_fifo_din[4]} {u_fifo_ctrl/fpga2pc_fifo_din[5]} {u_fifo_ctrl/fpga2pc_fifo_din[6]} {u_fifo_ctrl/fpga2pc_fifo_din[7]} {u_fifo_ctrl/fpga2pc_fifo_din[8]} {u_fifo_ctrl/fpga2pc_fifo_din[9]} {u_fifo_ctrl/fpga2pc_fifo_din[10]} {u_fifo_ctrl/fpga2pc_fifo_din[11]} {u_fifo_ctrl/fpga2pc_fifo_din[12]} {u_fifo_ctrl/fpga2pc_fifo_din[13]} {u_fifo_ctrl/fpga2pc_fifo_din[14]} {u_fifo_ctrl/fpga2pc_fifo_din[15]} {u_fifo_ctrl/fpga2pc_fifo_din[16]} {u_fifo_ctrl/fpga2pc_fifo_din[17]} {u_fifo_ctrl/fpga2pc_fifo_din[18]} {u_fifo_ctrl/fpga2pc_fifo_din[19]} {u_fifo_ctrl/fpga2pc_fifo_din[20]} {u_fifo_ctrl/fpga2pc_fifo_din[21]} {u_fifo_ctrl/fpga2pc_fifo_din[22]} {u_fifo_ctrl/fpga2pc_fifo_din[23]} {u_fifo_ctrl/fpga2pc_fifo_din[24]} {u_fifo_ctrl/fpga2pc_fifo_din[25]} {u_fifo_ctrl/fpga2pc_fifo_din[26]} {u_fifo_ctrl/fpga2pc_fifo_din[27]} {u_fifo_ctrl/fpga2pc_fifo_din[28]} {u_fifo_ctrl/fpga2pc_fifo_din[29]} {u_fifo_ctrl/fpga2pc_fifo_din[30]} {u_fifo_ctrl/fpga2pc_fifo_din[31]}]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {u_fifo_ctrl/tx_byte_num[0]} {u_fifo_ctrl/tx_byte_num[1]} {u_fifo_ctrl/tx_byte_num[2]} {u_fifo_ctrl/tx_byte_num[3]} {u_fifo_ctrl/tx_byte_num[4]} {u_fifo_ctrl/tx_byte_num[5]} {u_fifo_ctrl/tx_byte_num[6]} {u_fifo_ctrl/tx_byte_num[7]} {u_fifo_ctrl/tx_byte_num[8]} {u_fifo_ctrl/tx_byte_num[9]} {u_fifo_ctrl/tx_byte_num[10]} {u_fifo_ctrl/tx_byte_num[11]} {u_fifo_ctrl/tx_byte_num[12]} {u_fifo_ctrl/tx_byte_num[13]} {u_fifo_ctrl/tx_byte_num[14]} {u_fifo_ctrl/tx_byte_num[15]}]]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {u_fifo_ctrl/tx_fifo_dout[0]} {u_fifo_ctrl/tx_fifo_dout[1]} {u_fifo_ctrl/tx_fifo_dout[2]} {u_fifo_ctrl/tx_fifo_dout[3]} {u_fifo_ctrl/tx_fifo_dout[4]} {u_fifo_ctrl/tx_fifo_dout[5]} {u_fifo_ctrl/tx_fifo_dout[6]} {u_fifo_ctrl/tx_fifo_dout[7]} {u_fifo_ctrl/tx_fifo_dout[8]} {u_fifo_ctrl/tx_fifo_dout[9]} {u_fifo_ctrl/tx_fifo_dout[10]} {u_fifo_ctrl/tx_fifo_dout[11]} {u_fifo_ctrl/tx_fifo_dout[12]} {u_fifo_ctrl/tx_fifo_dout[13]} {u_fifo_ctrl/tx_fifo_dout[14]} {u_fifo_ctrl/tx_fifo_dout[15]} {u_fifo_ctrl/tx_fifo_dout[16]} {u_fifo_ctrl/tx_fifo_dout[17]} {u_fifo_ctrl/tx_fifo_dout[18]} {u_fifo_ctrl/tx_fifo_dout[19]} {u_fifo_ctrl/tx_fifo_dout[20]} {u_fifo_ctrl/tx_fifo_dout[21]} {u_fifo_ctrl/tx_fifo_dout[22]} {u_fifo_ctrl/tx_fifo_dout[23]} {u_fifo_ctrl/tx_fifo_dout[24]} {u_fifo_ctrl/tx_fifo_dout[25]} {u_fifo_ctrl/tx_fifo_dout[26]} {u_fifo_ctrl/tx_fifo_dout[27]} {u_fifo_ctrl/tx_fifo_dout[28]} {u_fifo_ctrl/tx_fifo_dout[29]} {u_fifo_ctrl/tx_fifo_dout[30]} {u_fifo_ctrl/tx_fifo_dout[31]}]]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list u_fifo_ctrl/pc2fpga_fifo_rden]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list u_fifo_ctrl/rec_fifo_wren]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list u_fifo_ctrl/tx_fifo_rden]]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list u_fifo_ctrl/tx_pkt_done]]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_gmii_to_rgmii/u_rgmii_rx/gmii_rx_clk]]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_fifo_ctrl/outState[0]} {u_fifo_ctrl/outState[1]} {u_fifo_ctrl/outState[2]}]]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_fifo_ctrl/outNum[0]} {u_fifo_ctrl/outNum[1]} {u_fifo_ctrl/outNum[2]} {u_fifo_ctrl/outNum[3]} {u_fifo_ctrl/outNum[4]} {u_fifo_ctrl/outNum[5]} {u_fifo_ctrl/outNum[6]} {u_fifo_ctrl/outNum[7]} {u_fifo_ctrl/outNum[8]} {u_fifo_ctrl/outNum[9]} {u_fifo_ctrl/outNum[10]} {u_fifo_ctrl/outNum[11]} {u_fifo_ctrl/outNum[12]} {u_fifo_ctrl/outNum[13]} {u_fifo_ctrl/outNum[14]} {u_fifo_ctrl/outNum[15]}]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_fifo_ctrl/outCounter[0]} {u_fifo_ctrl/outCounter[1]} {u_fifo_ctrl/outCounter[2]} {u_fifo_ctrl/outCounter[3]} {u_fifo_ctrl/outCounter[4]} {u_fifo_ctrl/outCounter[5]} {u_fifo_ctrl/outCounter[6]} {u_fifo_ctrl/outCounter[7]}]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_fifo_ctrl/tFpgaRead[0]} {u_fifo_ctrl/tFpgaRead[1]} {u_fifo_ctrl/tFpgaRead[2]} {u_fifo_ctrl/tFpgaRead[3]} {u_fifo_ctrl/tFpgaRead[4]} {u_fifo_ctrl/tFpgaRead[5]} {u_fifo_ctrl/tFpgaRead[6]} {u_fifo_ctrl/tFpgaRead[7]} {u_fifo_ctrl/tFpgaRead[8]} {u_fifo_ctrl/tFpgaRead[9]} {u_fifo_ctrl/tFpgaRead[10]} {u_fifo_ctrl/tFpgaRead[11]} {u_fifo_ctrl/tFpgaRead[12]} {u_fifo_ctrl/tFpgaRead[13]} {u_fifo_ctrl/tFpgaRead[14]} {u_fifo_ctrl/tFpgaRead[15]} {u_fifo_ctrl/tFpgaRead[16]} {u_fifo_ctrl/tFpgaRead[17]} {u_fifo_ctrl/tFpgaRead[18]} {u_fifo_ctrl/tFpgaRead[19]} {u_fifo_ctrl/tFpgaRead[20]} {u_fifo_ctrl/tFpgaRead[21]} {u_fifo_ctrl/tFpgaRead[22]} {u_fifo_ctrl/tFpgaRead[23]} {u_fifo_ctrl/tFpgaRead[24]} {u_fifo_ctrl/tFpgaRead[25]} {u_fifo_ctrl/tFpgaRead[26]} {u_fifo_ctrl/tFpgaRead[27]} {u_fifo_ctrl/tFpgaRead[28]} {u_fifo_ctrl/tFpgaRead[29]} {u_fifo_ctrl/tFpgaRead[30]} {u_fifo_ctrl/tFpgaRead[31]} {u_fifo_ctrl/tFpgaRead[32]} {u_fifo_ctrl/tFpgaRead[33]} {u_fifo_ctrl/tFpgaRead[34]} {u_fifo_ctrl/tFpgaRead[35]} {u_fifo_ctrl/tFpgaRead[36]} {u_fifo_ctrl/tFpgaRead[37]} {u_fifo_ctrl/tFpgaRead[38]} {u_fifo_ctrl/tFpgaRead[39]} {u_fifo_ctrl/tFpgaRead[40]} {u_fifo_ctrl/tFpgaRead[41]} {u_fifo_ctrl/tFpgaRead[42]} {u_fifo_ctrl/tFpgaRead[43]} {u_fifo_ctrl/tFpgaRead[44]} {u_fifo_ctrl/tFpgaRead[45]} {u_fifo_ctrl/tFpgaRead[46]} {u_fifo_ctrl/tFpgaRead[47]} {u_fifo_ctrl/tFpgaRead[48]} {u_fifo_ctrl/tFpgaRead[49]} {u_fifo_ctrl/tFpgaRead[50]} {u_fifo_ctrl/tFpgaRead[51]} {u_fifo_ctrl/tFpgaRead[52]} {u_fifo_ctrl/tFpgaRead[53]} {u_fifo_ctrl/tFpgaRead[54]} {u_fifo_ctrl/tFpgaRead[55]} {u_fifo_ctrl/tFpgaRead[56]} {u_fifo_ctrl/tFpgaRead[57]} {u_fifo_ctrl/tFpgaRead[58]} {u_fifo_ctrl/tFpgaRead[59]} {u_fifo_ctrl/tFpgaRead[60]} {u_fifo_ctrl/tFpgaRead[61]} {u_fifo_ctrl/tFpgaRead[62]} {u_fifo_ctrl/tFpgaRead[63]}]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_fifo_ctrl/tPcLoop[0]} {u_fifo_ctrl/tPcLoop[1]} {u_fifo_ctrl/tPcLoop[2]} {u_fifo_ctrl/tPcLoop[3]} {u_fifo_ctrl/tPcLoop[4]} {u_fifo_ctrl/tPcLoop[5]} {u_fifo_ctrl/tPcLoop[6]} {u_fifo_ctrl/tPcLoop[7]} {u_fifo_ctrl/tPcLoop[8]} {u_fifo_ctrl/tPcLoop[9]} {u_fifo_ctrl/tPcLoop[10]} {u_fifo_ctrl/tPcLoop[11]} {u_fifo_ctrl/tPcLoop[12]} {u_fifo_ctrl/tPcLoop[13]} {u_fifo_ctrl/tPcLoop[14]} {u_fifo_ctrl/tPcLoop[15]} {u_fifo_ctrl/tPcLoop[16]} {u_fifo_ctrl/tPcLoop[17]} {u_fifo_ctrl/tPcLoop[18]} {u_fifo_ctrl/tPcLoop[19]} {u_fifo_ctrl/tPcLoop[20]} {u_fifo_ctrl/tPcLoop[21]} {u_fifo_ctrl/tPcLoop[22]} {u_fifo_ctrl/tPcLoop[23]} {u_fifo_ctrl/tPcLoop[24]} {u_fifo_ctrl/tPcLoop[25]} {u_fifo_ctrl/tPcLoop[26]} {u_fifo_ctrl/tPcLoop[27]} {u_fifo_ctrl/tPcLoop[28]} {u_fifo_ctrl/tPcLoop[29]} {u_fifo_ctrl/tPcLoop[30]} {u_fifo_ctrl/tPcLoop[31]} {u_fifo_ctrl/tPcLoop[32]} {u_fifo_ctrl/tPcLoop[33]} {u_fifo_ctrl/tPcLoop[34]} {u_fifo_ctrl/tPcLoop[35]} {u_fifo_ctrl/tPcLoop[36]} {u_fifo_ctrl/tPcLoop[37]} {u_fifo_ctrl/tPcLoop[38]} {u_fifo_ctrl/tPcLoop[39]} {u_fifo_ctrl/tPcLoop[40]} {u_fifo_ctrl/tPcLoop[41]} {u_fifo_ctrl/tPcLoop[42]} {u_fifo_ctrl/tPcLoop[43]} {u_fifo_ctrl/tPcLoop[44]} {u_fifo_ctrl/tPcLoop[45]} {u_fifo_ctrl/tPcLoop[46]} {u_fifo_ctrl/tPcLoop[47]} {u_fifo_ctrl/tPcLoop[48]} {u_fifo_ctrl/tPcLoop[49]} {u_fifo_ctrl/tPcLoop[50]} {u_fifo_ctrl/tPcLoop[51]} {u_fifo_ctrl/tPcLoop[52]} {u_fifo_ctrl/tPcLoop[53]} {u_fifo_ctrl/tPcLoop[54]} {u_fifo_ctrl/tPcLoop[55]} {u_fifo_ctrl/tPcLoop[56]} {u_fifo_ctrl/tPcLoop[57]} {u_fifo_ctrl/tPcLoop[58]} {u_fifo_ctrl/tPcLoop[59]} {u_fifo_ctrl/tPcLoop[60]} {u_fifo_ctrl/tPcLoop[61]} {u_fifo_ctrl/tPcLoop[62]} {u_fifo_ctrl/tPcLoop[63]}]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_fifo_ctrl/tFpgaWrite[0]} {u_fifo_ctrl/tFpgaWrite[1]} {u_fifo_ctrl/tFpgaWrite[2]} {u_fifo_ctrl/tFpgaWrite[3]} {u_fifo_ctrl/tFpgaWrite[4]} {u_fifo_ctrl/tFpgaWrite[5]} {u_fifo_ctrl/tFpgaWrite[6]} {u_fifo_ctrl/tFpgaWrite[7]} {u_fifo_ctrl/tFpgaWrite[8]} {u_fifo_ctrl/tFpgaWrite[9]} {u_fifo_ctrl/tFpgaWrite[10]} {u_fifo_ctrl/tFpgaWrite[11]} {u_fifo_ctrl/tFpgaWrite[12]} {u_fifo_ctrl/tFpgaWrite[13]} {u_fifo_ctrl/tFpgaWrite[14]} {u_fifo_ctrl/tFpgaWrite[15]} {u_fifo_ctrl/tFpgaWrite[16]} {u_fifo_ctrl/tFpgaWrite[17]} {u_fifo_ctrl/tFpgaWrite[18]} {u_fifo_ctrl/tFpgaWrite[19]} {u_fifo_ctrl/tFpgaWrite[20]} {u_fifo_ctrl/tFpgaWrite[21]} {u_fifo_ctrl/tFpgaWrite[22]} {u_fifo_ctrl/tFpgaWrite[23]} {u_fifo_ctrl/tFpgaWrite[24]} {u_fifo_ctrl/tFpgaWrite[25]} {u_fifo_ctrl/tFpgaWrite[26]} {u_fifo_ctrl/tFpgaWrite[27]} {u_fifo_ctrl/tFpgaWrite[28]} {u_fifo_ctrl/tFpgaWrite[29]} {u_fifo_ctrl/tFpgaWrite[30]} {u_fifo_ctrl/tFpgaWrite[31]} {u_fifo_ctrl/tFpgaWrite[32]} {u_fifo_ctrl/tFpgaWrite[33]} {u_fifo_ctrl/tFpgaWrite[34]} {u_fifo_ctrl/tFpgaWrite[35]} {u_fifo_ctrl/tFpgaWrite[36]} {u_fifo_ctrl/tFpgaWrite[37]} {u_fifo_ctrl/tFpgaWrite[38]} {u_fifo_ctrl/tFpgaWrite[39]} {u_fifo_ctrl/tFpgaWrite[40]} {u_fifo_ctrl/tFpgaWrite[41]} {u_fifo_ctrl/tFpgaWrite[42]} {u_fifo_ctrl/tFpgaWrite[43]} {u_fifo_ctrl/tFpgaWrite[44]} {u_fifo_ctrl/tFpgaWrite[45]} {u_fifo_ctrl/tFpgaWrite[46]} {u_fifo_ctrl/tFpgaWrite[47]} {u_fifo_ctrl/tFpgaWrite[48]} {u_fifo_ctrl/tFpgaWrite[49]} {u_fifo_ctrl/tFpgaWrite[50]} {u_fifo_ctrl/tFpgaWrite[51]} {u_fifo_ctrl/tFpgaWrite[52]} {u_fifo_ctrl/tFpgaWrite[53]} {u_fifo_ctrl/tFpgaWrite[54]} {u_fifo_ctrl/tFpgaWrite[55]} {u_fifo_ctrl/tFpgaWrite[56]} {u_fifo_ctrl/tFpgaWrite[57]} {u_fifo_ctrl/tFpgaWrite[58]} {u_fifo_ctrl/tFpgaWrite[59]} {u_fifo_ctrl/tFpgaWrite[60]} {u_fifo_ctrl/tFpgaWrite[61]} {u_fifo_ctrl/tFpgaWrite[62]} {u_fifo_ctrl/tFpgaWrite[63]}]]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_fifo_ctrl/tMaxPcLoop[0]} {u_fifo_ctrl/tMaxPcLoop[1]} {u_fifo_ctrl/tMaxPcLoop[2]} {u_fifo_ctrl/tMaxPcLoop[3]} {u_fifo_ctrl/tMaxPcLoop[4]} {u_fifo_ctrl/tMaxPcLoop[5]} {u_fifo_ctrl/tMaxPcLoop[6]} {u_fifo_ctrl/tMaxPcLoop[7]} {u_fifo_ctrl/tMaxPcLoop[8]} {u_fifo_ctrl/tMaxPcLoop[9]} {u_fifo_ctrl/tMaxPcLoop[10]} {u_fifo_ctrl/tMaxPcLoop[11]} {u_fifo_ctrl/tMaxPcLoop[12]} {u_fifo_ctrl/tMaxPcLoop[13]} {u_fifo_ctrl/tMaxPcLoop[14]} {u_fifo_ctrl/tMaxPcLoop[15]} {u_fifo_ctrl/tMaxPcLoop[16]} {u_fifo_ctrl/tMaxPcLoop[17]} {u_fifo_ctrl/tMaxPcLoop[18]} {u_fifo_ctrl/tMaxPcLoop[19]} {u_fifo_ctrl/tMaxPcLoop[20]} {u_fifo_ctrl/tMaxPcLoop[21]} {u_fifo_ctrl/tMaxPcLoop[22]} {u_fifo_ctrl/tMaxPcLoop[23]} {u_fifo_ctrl/tMaxPcLoop[24]} {u_fifo_ctrl/tMaxPcLoop[25]} {u_fifo_ctrl/tMaxPcLoop[26]} {u_fifo_ctrl/tMaxPcLoop[27]} {u_fifo_ctrl/tMaxPcLoop[28]} {u_fifo_ctrl/tMaxPcLoop[29]} {u_fifo_ctrl/tMaxPcLoop[30]} {u_fifo_ctrl/tMaxPcLoop[31]} {u_fifo_ctrl/tMaxPcLoop[32]} {u_fifo_ctrl/tMaxPcLoop[33]} {u_fifo_ctrl/tMaxPcLoop[34]} {u_fifo_ctrl/tMaxPcLoop[35]} {u_fifo_ctrl/tMaxPcLoop[36]} {u_fifo_ctrl/tMaxPcLoop[37]} {u_fifo_ctrl/tMaxPcLoop[38]} {u_fifo_ctrl/tMaxPcLoop[39]} {u_fifo_ctrl/tMaxPcLoop[40]} {u_fifo_ctrl/tMaxPcLoop[41]} {u_fifo_ctrl/tMaxPcLoop[42]} {u_fifo_ctrl/tMaxPcLoop[43]} {u_fifo_ctrl/tMaxPcLoop[44]} {u_fifo_ctrl/tMaxPcLoop[45]} {u_fifo_ctrl/tMaxPcLoop[46]} {u_fifo_ctrl/tMaxPcLoop[47]} {u_fifo_ctrl/tMaxPcLoop[48]} {u_fifo_ctrl/tMaxPcLoop[49]} {u_fifo_ctrl/tMaxPcLoop[50]} {u_fifo_ctrl/tMaxPcLoop[51]} {u_fifo_ctrl/tMaxPcLoop[52]} {u_fifo_ctrl/tMaxPcLoop[53]} {u_fifo_ctrl/tMaxPcLoop[54]} {u_fifo_ctrl/tMaxPcLoop[55]} {u_fifo_ctrl/tMaxPcLoop[56]} {u_fifo_ctrl/tMaxPcLoop[57]} {u_fifo_ctrl/tMaxPcLoop[58]} {u_fifo_ctrl/tMaxPcLoop[59]} {u_fifo_ctrl/tMaxPcLoop[60]} {u_fifo_ctrl/tMaxPcLoop[61]} {u_fifo_ctrl/tMaxPcLoop[62]} {u_fifo_ctrl/tMaxPcLoop[63]}]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets eth_txc_OBUF]
