# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Administrator/Desktop/21_eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/sync_fifo_2048x32b/sync_fifo_2048x32b.xci
# IP: The module: 'sync_fifo_2048x32b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/21_eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/sync_fifo_2048x32b/sync_fifo_2048x32b.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_2048x32b'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/21_eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/sync_fifo_2048x32b/sync_fifo_2048x32b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_2048x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Administrator/Desktop/21_eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/sync_fifo_2048x32b/sync_fifo_2048x32b.xci
# IP: The module: 'sync_fifo_2048x32b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/21_eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/sync_fifo_2048x32b/sync_fifo_2048x32b.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_2048x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/21_eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/sync_fifo_2048x32b/sync_fifo_2048x32b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sync_fifo_2048x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
